---
- hosts: bastion_amazon

#  pre_tasks:
#  - name: Import EPEL GPG key
#    become: yes
#    ansible.builtin.rpm_key:
#      state: present
#      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
#  - name: Install EPEL Repo
#    become: yes
#    ansible.builtin.dnf:
#      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
#      state: present
#  - name: OS Update
#    become: yes
#    ansible.builtin.dnf:
#      name: '*'
#      state: latest
  roles:
#  - basic
  - ldap
#  - monitoring
#  - openShift
